version: 2.1

executors:
  main-executor:
    docker:
      - image: circleci/node:lts

jobs:
  quality-check:
    executor: main-executor
    steps:
      - checkout
      - run: npm ci
      - run: npm run prettier:check
      - run: npm run typecheck

  deploy:
    executor: main-executor
    parameters:
      clever-app-id:
        type: string
    steps:
      - checkout
      - run: |
          sudo npm install --global clever-tools
          clever login --token=$CLEVER_TOKEN --secret=$CLEVER_SECRET
          clever link << parameters.clever-app-id >>
          clever deploy --force

workflows:
  version: 2

  deploy:
    jobs:
      - quality-check:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          name: deploy-staging
          clever-app-id: app_e7d3b441-d794-4ef9-b337-d4cc0a048175
          requires:
            - quality-check
          context: clever-cloud2-zenika-dev
          filters:
            branches:
              only: main
      - deploy:
          name: deploy-production
          clever-app-id: app_51d6df67-b2b9-4aa4-b285-b3ff167c54b9
          requires:
            - quality-check
          context: clever-cloud2-zenika-dev
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
